#!/bin/bash

CONFIG_LIST=\
"CONFIG_E1000 \
 CONFIG_E1000E \
 CONFIG_IGB \
 CONFIG_IXGB \
 CONFIG_IXGBE \
 CONFIG_IXGBEVF \
 CONFIG_ENA_ETHERNET \
 CONFIG_8139CP \
 CONFIG_8139TOO \
 CONFIG_VIRTIO \
 CONFIG_VIRTIO_NET \
 CONFIG_VMXNET3 \
 CONFIG_HYPERV_NET \
 CONFIG_HUGETLBFS \
 CONFIG_HUGETLB_PAGE \
 CONFIG_MLX4_EN \
 CONFIG_MLX5_CORE \
 CONFIG_TUN \
 CONFIG_TAP \
 CONFIG_HYPERV_KEYBOARD \
 CONFIG_HID_HYPERV_MOUSE \
 CONFIG_HYPERV \
 CONFIG_HYPERV_TSCPAGE \
 CONFIG_HYPERV_UTILS \
 CONFIG_HYPERV_BALLOON \
 CONFIG_HYPERV_STORAGE \
 CONFIG_HYPERV_VSOCKETS \
 CONFIG_OPENVSWITCH \
 CONFIG_NET_INGRESS \
"

LINUX_YOCTO_DIR=$YOCTO_ROOT/tmp/work/changeling_hypervisor-spirent-linux/linux-yocto
LINUX_VER=$(ls $LINUX_YOCTO_DIR)
KBUILD_DIR=${LINUX_YOCTO_DIR}/${LINUX_VER}/linux-changeling_hypervisor-standard-build
#echo $KBUILD_DIR

for i in $CONFIG_LIST
do
	grep -w $i ${KBUILD_DIR}/.config
done

